// Generated by gencpp from file vision_msgs/ImageQuality.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_IMAGEQUALITY_H
#define VISION_MSGS_MESSAGE_IMAGEQUALITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct ImageQuality_
{
  typedef ImageQuality_<ContainerAllocator> Type;

  ImageQuality_()
    : header()
    , brightness(0.0)
    , sharpness(0.0)
    , brightness_delta(0.0)
    , sharpness_delta(0.0)  {
    }
  ImageQuality_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , brightness(0.0)
    , sharpness(0.0)
    , brightness_delta(0.0)
    , sharpness_delta(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _brightness_type;
  _brightness_type brightness;

   typedef float _sharpness_type;
  _sharpness_type sharpness;

   typedef float _brightness_delta_type;
  _brightness_delta_type brightness_delta;

   typedef float _sharpness_delta_type;
  _sharpness_delta_type sharpness_delta;




  typedef boost::shared_ptr< ::vision_msgs::ImageQuality_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::ImageQuality_<ContainerAllocator> const> ConstPtr;

}; // struct ImageQuality_

typedef ::vision_msgs::ImageQuality_<std::allocator<void> > ImageQuality;

typedef boost::shared_ptr< ::vision_msgs::ImageQuality > ImageQualityPtr;
typedef boost::shared_ptr< ::vision_msgs::ImageQuality const> ImageQualityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::ImageQuality_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::ImageQuality_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'vision_msgs': ['/home/peggyjean/toms_ws/src/vision_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::ImageQuality_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::ImageQuality_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::ImageQuality_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::ImageQuality_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::ImageQuality_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::ImageQuality_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::ImageQuality_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3839252c986c29ecf4e52d533209c6b";
  }

  static const char* value(const ::vision_msgs::ImageQuality_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3839252c986c29eULL;
  static const uint64_t static_value2 = 0xcf4e52d533209c6bULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::ImageQuality_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/ImageQuality";
  }

  static const char* value(const ::vision_msgs::ImageQuality_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::ImageQuality_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header for timestamp info\n\
Header header\n\
float32 brightness\n\
float32 sharpness\n\
float32 brightness_delta\n\
float32 sharpness_delta\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vision_msgs::ImageQuality_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::ImageQuality_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.brightness);
      stream.next(m.sharpness);
      stream.next(m.brightness_delta);
      stream.next(m.sharpness_delta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageQuality_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::ImageQuality_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::ImageQuality_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "brightness: ";
    Printer<float>::stream(s, indent + "  ", v.brightness);
    s << indent << "sharpness: ";
    Printer<float>::stream(s, indent + "  ", v.sharpness);
    s << indent << "brightness_delta: ";
    Printer<float>::stream(s, indent + "  ", v.brightness_delta);
    s << indent << "sharpness_delta: ";
    Printer<float>::stream(s, indent + "  ", v.sharpness_delta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_IMAGEQUALITY_H
